import cv2
import numpy as np
import matplotlib.pyplot as plt
img = cv2.imread(r"C:\Users\ASUS\Desktop\image mid\images\face grayscale.jpg")
img_gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_gray_20 = img_gray.copy()
img_gray_40 = img_gray.copy()
img_gray_60 = img_gray.copy()
img_gray15 = img_gray.copy()
img_gray25 = img_gray.copy()
img_gray50 = img_gray.copy()
height = img_gray.shape[0]
width = img_gray.shape[1]
for i in range(0, height):
  for j in range(0, width):
    img_gray_20[i][j]=np.power(img_gray[i][j],0.20)
    img_gray_40[i][j]=np.power(img_gray[i][j],0.40)
    img_gray_60[i][j]=np.power(img_gray[i][j], 0.60)
    img_gray15[i][j]=np.power(img_gray[i][j], 1.5)
    img_gray25[i][j]=np.power(img_gray[i][j], 2.5)
    img_gray50[i][j]=np.power(img_gray[i][j], 5)
plt.figure(figsize=(10,10))
plt.subplot(4,4,1)
plt.imshow(img_gray_20, cmap='gray')
plt.title('Gamma =0.20')
plt.subplot(4,4,2)
plt.imshow(img_gray_40, cmap='gray')
plt.title('Gamma = 0.40')
plt.subplot(4,4,3)
plt.imshow(img_gray_60, cmap='gray')
plt.title('Gamma = 0.60')
plt.subplot(4,4,4)
plt.imshow(img_gray, cmap='gray')
plt.title('Original Image Gamma = 1')
plt.subplot(4,4,5)
plt.imshow(img_gray15, cmap='gray')
plt.title('Gamma = 1.5')
plt.subplot(4,4,6)
plt.imshow(img_gray25, cmap='gray')
plt.title('Gamma = 2.5')
plt.subplot(4,4,7)
plt.imshow(img_gray50, cmap='gray')
plt.title('Gamma = 5')

img_gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
r = np.unique(img_gray)
s= np.zeros(len(r))
s_20 = np.zeros(len(r))
s_40 = np.zeros(len(r))
s_60 = np.zeros(len(r))
s_15 = np.zeros(len(r))
s_25 = np.zeros(len(r))
s_50 = np.zeros(len(r))
for i in range(0, len(r)):
  s[i] = np. power(r[i],1)
  s_20[i] = np. power(r[i], 0.20)
  s_40[i] = np. power(r[i], 0.40)
  s_60[i] = np. power(r[i], 0.60)
  s_15[i] = np. power(r[i], 1.5)
  s_25[i] = np. power(r[i], 2.5)
  s_50[i] = np. power(r[i], 5)
plt.subplot(4,4,9)
plt.plot(r,s_20)
plt.title('Gamma = 0.20')
plt.subplot(4,4,10)
plt.plot(r,s_40)
plt.title('Gamma = 0.40')
plt.subplot(4,4,11)
plt.plot(r,s_60)
plt.title('Gamma = 0.60')
plt.subplot(4,4,12)
plt.plot(r,s)
plt.title('Original Image Gamma = 1')
plt.subplot(4,4,13)
plt.plot(r,s_15)
plt.title('Gamma = 1.5')
plt.subplot(4,4,14)
plt.plot(r,s_25)
plt.title('Gamma = 2.5')
plt.subplot(4,4,15)
plt.plot(r,s_50)
plt.title('Gamma = 5')
plt.tight_layout()
plt.show()